"""create roles table

Revision ID: 0bebee3c7df8
Revises: 
Create Date: 2026-03-25 11:13:19.052426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bebee3c7df8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canchas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo_grama', sa.Enum('SINTETICA', 'NATURAL', name='tipograma'), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('precio_hora', sa.Float(), nullable=False),
    sa.Column('es_techada', sa.Boolean(), nullable=True),
    sa.Column('esta_disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canchas_id'), 'canchas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canchas_id'), table_name='canchas')
    op.drop_table('canchas')
    # ### end Alembic commands ###
