"""add location field to canchas

Revision ID: 2ffe075dc487
Revises: 0bebee3c7df8
Create Date: 2026-03-25 17:05:39.737919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffe075dc487'
down_revision: Union[str, Sequence[str], None] = '0bebee3c7df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canchas', sa.Column('ubicacion', sa.String(), server_default='Dirección no especificada', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('canchas', 'ubicacion')
    # ### end Alembic commands ###
